### ISSUE TITLE
Syntax error in edge.rb

### ISSUE THREAD

**Issue by fteem** [CoralineAda/society#4]
Hello
I am getting an error when using the gem: 

```
*snip*

society-1.2.0/lib/society/edge.rb:14: syntax error, unexpected ',' (SyntaxError)
    def initialize(to:, weight: 1)

*snip*
```

[This](https://github.com/CoralineAda/society/blob/master/lib/society/edge.rb#L14) does look like a syntax error?

Thanks!

**Comment by CoralineAda** [comment]
What version of Ruby are you using?

**Comment by fteem** [comment]
Ruby 2.0.0-p353, OSX Yosemite

**Comment by CoralineAda** [comment]
Ah, that explains it. It uses named keywords, so you need 2.1 or higher. Updated the README.

**Comment by fteem** [comment]
Well, that explains everything! Thanks!
