### ISSUE TITLE
JS control to filter objects on the graph

### ISSUE THREAD

**Issue by CoralineAda** [CoralineAda/society#9]
I would love for someone to submit a PR that accomplishes this. I am envisioning a type-ahead text box or a dropdown of all classes that, when a single class is selected, narrows the scope of the graph down to that class and its relations.

I have talked to @theotherzach about implementing this, so have at it, Zach! :)

**Comment by elight** [comment]
Yep. That's where I started when I began work on #11–until I realized that munging the CSS would be a lot easier than munging the data.  I'd still prefer a solution to this issue over my #11 PR.

**Comment by theotherzach** [comment]
Still on my radar. I just finished a side project so I'll be able to take a look at this soon.

**Comment by elight** [comment]
What I want for this, in my heart of hearts, is to be able to specify a list of matchers/regexps so I can get the **exact** subset of classes that I need to examine for dependencies.

**Comment by elight** [comment]
Aaaand this sounds like a separate issue. ;-)

**Comment by elight** [comment]
Opened #17 accordingly
